# Generated by Django 5.1.2 on 2024-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clima', models.JSONField()),
                ('actividades', models.JSONField()),
                ('presupuesto', models.JSONField()),
                ('preferencias_culturales', models.JSONField()),
                ('edad_recomendada', models.JSONField()),
                ('idioma_local', models.JSONField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
